name: Beta
on:
  push:
    tags:
      - v*-beta

jobs:
  pre-release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v3
        with: { go-version: 1.19 }

      - uses: actions/setup-node@v3
        with: { node-version: '16' }

      - run: go install github.com/go-task/task/v3/cmd/task@latest

      - run: sudo apt update && sudo apt-get install rpm

      - uses: actions/checkout@v3

      - run: task deps

      - run: echo ${{ secrets.GPG_KEY }} | tr " " "\n" | base64 -d | gpg --import --batch

      - run: gpg --sign -u "F054 01BF 5EC9 2B45 AC03 D511 55DC 74D9 F0AF F3B6" --pinentry-mode loopback --yes --batch --passphrase "${{ secrets.GPG_PASS }}" --output unlock.sig --detach-sign README.md

      - run: rm -f unlock.sig

      - run:  git reset --hard

      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} task release:prod


  deploy-beta:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v3
        with: { go-version: 1.19 }

      - run: go install github.com/go-task/task/v3/cmd/task@latest

      - uses: actions/checkout@v3

      - run: context=prod task docker:test

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./deployment/docker/prod/buildx.Dockerfile
          push: true
          tags: ghcr.io/pierrickbrun/semaphore:beta,ghcr.io/pierrickbrun/semaphore:${{ github.ref_name }}



      - name: Build and push runner
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./deployment/docker/prod/runner.buildx.Dockerfile
          push: true
          tags: ghcr.io/pierrickbrun/runner:beta,ghcr.io/pierrickbrun/runner:${{ github.ref_name }}